# Generated by Django 3.1.2 on 2020-10-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanagement',
            name='task_no',
            field=models.IntegerField(null=True),
        ),
    ]
